version: 2.1

jobs:
  job_a:
    executor:
      docker:
        - image: cimg/base:stable
      resource_class: small
    steps:
      - checkout
      - run: echo hello 1
  job_b:
    executor:
      docker:
        - image: cimg/base:stable
      resource_class: large
    steps:
      - checkout
      - run: echo hello 2

workflows:
  job-workflow:
    jobs:
      - job_a
      - job_b